### ISSUE TITLE
Return objects instead of Arrays.

### ISSUE THREAD

**Issue by ivmelo** [ivmelo/suap-client#1]

**Comment by JoabMendes** [comment]
Arrays are fine and faster. :wink:

**Comment by ivmelo** [comment]
I know, but some people have OCD.

**Comment by JoabMendes** [comment]
KEK
![OCD](https://media.giphy.com/media/iTOSoEs4eFwqs/giphy.gif)

**Comment by ivmelo** [comment]
@jeanjar, se quiser esse é teu. Mas tem que ser opcional. Arrays e objetos. :P
