### ISSUE TITLE
Bug da disciplina "Seminário de Integração Acadêmica"

### ISSUE THREAD

**Issue by yvescabral** [ivmelo/suap-client#13]
A disciplina Seminário de Integração Acadêmica, comum à grade de todos os cursos de nível tanto técnico quanto superior, tem uma formatação diferente das demais disciplinas, causando erro no momento de pegar as notas do boletim. Exemplo:
![Bug](https://cloud.githubusercontent.com/assets/3816749/17672969/53477122-62f5-11e6-824e-81f32496287d.PNG)

**Comment by ivmelo** [comment]
Este bug previne os usuários do 1º semestre a se cadastrarem no bot.. Tem que consertar ASAP.

@JoabMendes se quiser fazer aqui...

**Comment by JoabMendes** [comment]
Verei.

**Comment by ivmelo** [comment]
@JoabMendes Resolvi.
